spring.application.name=recipe-management
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/recipedb
spring.datasource.username=root
spring.datasource.password=Buna@rb7537
spring.jpa.hibernate.ddl-auto=update
